static constexpr char InstrumentNames[][32] PROGMEM =
{
 /*   0  */ "        Acoustic Grand Piano",
 /*   1  */ "       Bright Acoustic Piano",
 /*   2  */ "        Electric Grand Piano",
 /*   3  */ "            Honky-tonk Piano",
 /*   4  */ "            Electric Piano 1",
 /*   5  */ "            Electric Piano 2",
 /*   6  */ "                 Harpsichord",
 /*   7  */ "                    Clavinet",
 /*   8  */ "                     Celesta",
 /*   9  */ "                Glockenspiel",
 /*  10  */ "                   Music Box",
 /*  11  */ "                  Vibraphone",
 /*  12  */ "                     Marimba",
 /*  13  */ "                   Xylophone",
 /*  14  */ "               Tubular Bells",
 /*  15  */ "                    Dulcimer",
 /*  16  */ "               Drawbar Organ",
 /*  17  */ "            Percussive Organ",
 /*  18  */ "                  Rock Organ",
 /*  19  */ "                Church Organ",
 /*  20  */ "                  Reed Organ",
 /*  21  */ "                   Accordion",
 /*  22  */ "                   Harmonica",
 /*  23  */ "             Tango Accordion",
 /*  24  */ "     Acoustic Guitar (nylon)",
 /*  25  */ "     Acoustic Guitar (steel)",
 /*  26  */ "      Electric Guitar (jazz)",
 /*  27  */ "     Electric Guitar (clean)",
 /*  28  */ "     Electric Guitar (muted)",
 /*  29  */ "           Overdriven Guitar",
 /*  30  */ "           Distortion Guitar",
 /*  31  */ "            Guitar Harmonics",
 /*  32  */ "               Acoustic Bass",
 /*  33  */ "      Electric Bass (finger)",
 /*  34  */ "        Electric Bass (pick)",
 /*  35  */ "               Fretless Bass",
 /*  36  */ "                 Slap Bass 1",
 /*  37  */ "                 Slap Bass 2",
 /*  38  */ "                Synth Bass 1",
 /*  39  */ "                Synth Bass 2",
 /*  40  */ "                      Violin",
 /*  41  */ "                       Viola",
 /*  42  */ "                       Cello",
 /*  43  */ "                  Contrabass",
 /*  44  */ "             Tremolo Strings",
 /*  45  */ "           Pizzicato Strings",
 /*  46  */ "             Orchestral Harp",
 /*  47  */ "                     Timpani",
 /*  48  */ "           String Ensemble 1",
 /*  49  */ "           String Ensemble 2",
 /*  50  */ "             Synth Strings 1",
 /*  51  */ "             Synth Strings 2",
 /*  52  */ "                  Choir Aahs",
 /*  53  */ "                  Voice Oohs",
 /*  54  */ "                 Synth Choir",
 /*  55  */ "               Orchestra Hit",
 /*  56  */ "                     Trumpet",
 /*  57  */ "                    Trombone",
 /*  58  */ "                        Tuba",
 /*  59  */ "               Muted Trumpet",
 /*  60  */ "                 French Horn",
 /*  61  */ "               Brass Section",
 /*  62  */ "               Synth Brass 1",
 /*  63  */ "               Synth Brass 2",
 /*  64  */ "                 Soprano Sax",
 /*  65  */ "                    Alto Sax",
 /*  66  */ "                   Tenor Sax",
 /*  67  */ "                Baritone Sax",
 /*  68  */ "                        Oboe",
 /*  69  */ "                English Horn",
 /*  70  */ "                     Bassoon",
 /*  71  */ "                    Clarinet",
 /*  72  */ "                     Piccolo",
 /*  73  */ "                       Flute",
 /*  74  */ "                    Recorder",
 /*  75  */ "                   Pan Flute",
 /*  76  */ "                Blown bottle",
 /*  77  */ "                  Shakuhachi",
 /*  78  */ "                     Whistle",
 /*  79  */ "                     Ocarina",
 /*  80  */ "             Lead 1 (square)",
 /*  81  */ "           Lead 2 (sawtooth)",
 /*  82  */ "           Lead 3 (calliope)",
 /*  83  */ "              Lead 4 (chiff)",
 /*  84  */ "            Lead 5 (charang)",
 /*  85  */ "              Lead 6 (voice)",
 /*  86  */ "             Lead 7 (fifths)",
 /*  87  */ "        Lead 8 (bass + lead)",
 /*  88  */ "             Pad 1 (new age)",
 /*  89  */ "                Pad 2 (warm)",
 /*  90  */ "           Pad 3 (polysynth)",
 /*  91  */ "               Pad 4 (choir)",
 /*  92  */ "               Pad 5 (bowed)",
 /*  93  */ "            Pad 6 (metallic)",
 /*  94  */ "                Pad 7 (halo)",
 /*  95  */ "               Pad 8 (sweep)",
 /*  96  */ "                 FX 1 (rain)",
 /*  97  */ "           FX 2 (soundtrack)",
 /*  98  */ "              FX 3 (crystal)",
 /*  99  */ "           FX 4 (atmosphere)",
 /* 100  */ "           FX 5 (brightness)",
 /* 101  */ "              FX 6 (goblins)",
 /* 102  */ "               FX 7 (echoes)",
 /* 103  */ "               FX 8 (sci-fi)",
 /* 104  */ "                       Sitar",
 /* 105  */ "                       Banjo",
 /* 106  */ "                    Shamisen",
 /* 107  */ "                        Koto",
 /* 108  */ "                     Kalimba",
 /* 109  */ "                     Bagpipe",
 /* 110  */ "                      Fiddle",
 /* 111  */ "                      Shanai",
 /* 112  */ "                 Tinkle Bell",
 /* 113  */ "                       Agogo",
 /* 114  */ "                 Steel Drums",
 /* 115  */ "                   Woodblock",
 /* 116  */ "                  Taiko Drum",
 /* 117  */ "                 Melodic Tom",
 /* 118  */ "                  Synth Drum",
 /* 119  */ "              Reverse Cymbal",
 /* 120  */ "           Guitar Fret Noise",
 /* 121  */ "                Breath Noise",
 /* 122  */ "                    Seashore",
 /* 123  */ "                  Bird Tweet",
 /* 124  */ "              Telephone Ring",
 /* 125  */ "                  Helicopter",
 /* 126  */ "                    Applause",
 /* 127  */ "                     Gunshot",
 /* 128  */ "                 Bass Drum 2",
 /* 129  */ "                 Bass Drum 1",
 /* 130  */ "          Side Stick/Rimshot",
 /* 131  */ "                Snare Drum 1",
 /* 132  */ "                   Hand Clap",
 /* 133  */ "                Snare Drum 2",
 /* 134  */ "                   Low Tom 2",
 /* 135  */ "               Closed Hi-hat",
 /* 136  */ "                   Low Tom 1",
 /* 137  */ "                Pedal Hi-hat",
 /* 138  */ "                   Mid Tom 2",
 /* 139  */ "                 Open Hi-hat",
 /* 140  */ "                   Mid Tom 1",
 /* 141  */ "                  High Tom 2",
 /* 142  */ "              Crash Cymbal 1",
 /* 143  */ "                  High Tom 1",
 /* 144  */ "               Ride Cymbal 1",
 /* 145  */ "              Chinese Cymbal",
 /* 146  */ "                   Ride Bell",
 /* 147  */ "                  Tambourine",
 /* 148  */ "               Splash Cymbal",
 /* 149  */ "                     Cowbell",
 /* 150  */ "              Crash Cymbal 2",
 /* 151  */ "                  Vibra Slap",
 /* 152  */ "               Ride Cymbal 2",
 /* 153  */ "                  High Bongo",
 /* 154  */ "                   Low Bongo",
 /* 155  */ "             Mute High Conga",
 /* 156  */ "             Open High Conga",
 /* 157  */ "                   Low Conga",
 /* 158  */ "                High Timbale",
 /* 159  */ "                 Low Timbale",
 /* 160  */ "                  High Agogô",
 /* 161  */ "                   Low Agogô",
 /* 162  */ "                      Cabasa",
 /* 163  */ "                     Maracas",
 /* 164  */ "               Short Whistle",
 /* 165  */ "                Long Whistle",
 /* 166  */ "                 Short Güiro",
 /* 167  */ "                  Long Güiro",
 /* 168  */ "                      Claves",
 /* 169  */ "             High Wood Block",
 /* 170  */ "              Low Wood Block",
 /* 171  */ "                  Mute Cuíca",
 /* 172  */ "                  Open Cuíca",
 /* 173  */ "               Mute Triangle",
 /* 174  */ "               Open Triangle"
};

